Repository dymensionxyz/dymension, pull requests merged in 2023-01, with the labels that each got.

#147 Liorzilp/145 upgrade sdk v0.45.10
  go.mod
  go.sum
  x/rollapp/ibc_client_hooks_test.go
  x/rollapp/keeper/params_test.go
  x/sequencer/keeper/grpc_query_sequencers_by_rollapp_test.go
Labels: dependencies

#148 Liorzilp/146 support packet forward middleware
  app/app.go
  go.mod
  go.sum
  testing/dymint_test_chain_warpper.go
  testing/irc_test.go
  testing/utils.go
Labels: IRC

#158 fix sdkerrors.ErrLogic
  x/rollapp/keeper/grpc_query_get_state_info_by_height.go
  x/rollapp/keeper/grpc_query_get_state_info_by_height_test.go
Labels: bug

#161 change DefaultDisputePeriodInBlocks
  x/rollapp/types/params.go
Labels: C:rollapp

#176 Added variables to the configuration script
  scripts/setup_local.sh
Labels: T:devops

#179 check revision format in create rollapp instead of IBC hooks
  x/rollapp/ibc_client_hooks.go
  x/rollapp/ibc_client_hooks_test.go
  x/rollapp/keeper/grpc_query_get_state_info_by_height.go
  x/rollapp/keeper/grpc_query_get_state_info_by_height_test.go
  x/rollapp/keeper/msg_server_update_state.go
  x/rollapp/keeper/msg_server_update_state_test.go
  x/rollapp/types/errors.go
  x/rollapp/types/message_create_rollapp.go
  x/rollapp/types/message_create_rollapp_test.go
  x/sequencer/keeper/keeper_integration_test.go
  x/sequencer/keeper/msg_server_create_sequencer.go
  x/sequencer/types/errors.go
Labels: bug, c:ibc

#185 Mtsitrin/184 add setup script for 2nd node in local testnet
  scripts/set_validator.sh
  scripts/setup_local.sh
Labels: T:devops
